<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>5808aa86eb7ce0ba5e8726fc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-03 15:32:16</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1020-1.200.000.440.Release</buildsignature><categoryid>asm.py:1031</categoryid><desyncid>5808aa86eb7ce0ba5e8726fc</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: ASM :: Carry_GenericObject (HANDLE :: 7504)&gt;: Attempt to traverse between two states (pickup -&gt; exit) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF48E4C35D0; to 'object_sim' at 0x00007FF4B0510710&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'carryObject': (&lt;weakref at 0x00007FF4C8200F18; to 'book_Homework_University' at 0x00007FF4BC03F9D0&gt;, None, &lt;AnimationParticipant.CONTAINER = 102&gt;)})&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_utils.py", line 321, in holster&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\asm.py", line 1031, in request&#13;&#10;RuntimeError: ASM :: Carry_GenericObject (HANDLE :: 7504)&gt;: Attempt to traverse between two states (pickup -&gt; exit) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF48E4C35D0; to 'object_sim' at 0x00007FF4B0510710&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'carryObject': (&lt;weakref at 0x00007FF4C8200F18; to 'book_Homework_University' at 0x00007FF4BC03F9D0&gt;, None, &lt;AnimationParticipant.CONTAINER = 102&gt;)}&#13;&#10;rtim=0&#13;&#10;Client Session Time: 34.74&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: Intel(R) HD Graphics igdumd64.dll 8.15.10.2900, GUID: D7B78E66-4306-11CF-9D79-0820B2C2C535&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5808aa86eb7ce0ba5e8726fc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-04 14:36:43</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1020-1.200.000.440.Release</buildsignature><categoryid>commodity.py:1210</categoryid><desyncid>5808aa86eb7ce0ba5e8726fc</desyncid><systemconfig/><screenshot/><desyncdata>[tingyul] Exception thrown while loading an object in an inventory. &#13;&#10;Object: object_University_TermPresentation_ClassA:0x0000000000000000 Owner:  (AttributeError: 'NoneType' object has no attribute 'owner')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 206, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 477, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 679, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 817, in _spawn_next_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 851, in _spawn_requested_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 448, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 1946, in create_sim_instance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 183, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 575, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 181, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 87, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 305, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 2557, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 724, in load_items&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 137, in _load_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 734, in _create_inventory_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 191, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 734, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 742, in _post_create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1258, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2056, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2139, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\statistic_component.py", line 1165, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity_tracker.py", line 198, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 2103, in load_statistic_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 1230, in load_statistic_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity_tracker.py", line 64, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_tracker.py", line 406, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1892, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 294, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic.py", line 275, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic.py", line 290, in _notify_change&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 706, in _update_callback_listeners&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_listener.py", line 76, in trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1236, in _update_state_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1210, in _commodity_telemetry&#13;&#10;AttributeError: 'NoneType' object has no attribute 'owner'&#13;&#10;rtim=0&#13;&#10;Client Session Time: 34.74&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: Intel(R) HD Graphics igdumd64.dll 8.15.10.2900, GUID: D7B78E66-4306-11CF-9D79-0820B2C2C535&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5808aa86eb7ce0ba5e8726fc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-04 14:39:12</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1020-1.200.000.440.Release</buildsignature><categoryid>commodity.py:1210</categoryid><desyncid>5808aa86eb7ce0ba5e8726fc</desyncid><systemconfig/><screenshot/><desyncdata>[tingyul] Exception thrown while loading an object in an inventory. &#13;&#10;Object: object_University_TermPresentation_ClassB:0x0000000000000000 Owner:  (AttributeError: 'NoneType' object has no attribute 'owner')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 206, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 477, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 679, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 817, in _spawn_next_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 851, in _spawn_requested_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 448, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 1946, in create_sim_instance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 183, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 575, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 181, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 87, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 305, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 2557, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 724, in load_items&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 137, in _load_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 734, in _create_inventory_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 191, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 734, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 742, in _post_create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1258, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2056, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2139, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\statistic_component.py", line 1165, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity_tracker.py", line 198, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 2103, in load_statistic_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 1230, in load_statistic_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity_tracker.py", line 64, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_tracker.py", line 406, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1892, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 294, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic.py", line 275, in set_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic.py", line 290, in _notify_change&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\continuous_statistic.py", line 706, in _update_callback_listeners&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_listener.py", line 76, in trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1236, in _update_state_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1210, in _commodity_telemetry&#13;&#10;AttributeError: 'NoneType' object has no attribute 'owner'&#13;&#10;rtim=0&#13;&#10;Client Session Time: 34.74&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: Intel(R) HD Graphics igdumd64.dll 8.15.10.2900, GUID: D7B78E66-4306-11CF-9D79-0820B2C2C535&#13; &#10;</desyncdata></report>
</root>