<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 21:58:38</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>posture_state.py:152</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(stand:645, posture_CarryNothing:646, posture_CarryObject:683) and carry aspects (posture_CarryNothing(646, None), posture_CarryObject(683, object_Food_EggsBenedict:0x0b040b25be8e0b7c)), ')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 133, in _start_carried_linked_posture_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 118, in set_target_linked_posture_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture_state.py", line 152, in __init__&#13;&#10;KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(stand:645, posture_CarryNothing:646, posture_CarryObject:683) and carry aspects (posture_CarryNothing(646, None), posture_CarryObject(683, object_Food_EggsBenedict:0x0b040b25be8e0b7c)), '&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:10</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1462</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.terrian_MarchAround'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(&lt;class 'sims4.tuning.instances.posture_IslandCanoe'&gt;, &lt;class 'sims4.tuning.instances.posture_WaterScooter'&gt;, &lt;class 'sims4.tuning.instances.posture_IslandCanoe_Sit'&gt;, &lt;class 'sims4.tuning.instances.posture_IslandCanoe_Stand'&gt;), required_postures=(), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1462, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:17</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1462</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.sim_BeAffectionate'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(&lt;class 'sims4.tuning.instances.posture_SitIntimate'&gt;, &lt;class 'sims4.tuning.instances.posture_MonkeyBarsHangOut'&gt;, &lt;class 'sims4.tuning.instances.posture_SitTogether'&gt;, &lt;class 'sims4.tuning.instances.posture_SitIntimateBooth'&gt;), required_postures=(), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1462, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:18</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1462</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.sim_CallOver'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(&lt;class 'sims4.tuning.instances.posture_HottubWoohoo'&gt;, &lt;class 'sims4.tuning.instances.posture_HotTubSit'&gt;, &lt;class 'sims4.tuning.instances.posture_HotTubStand'&gt;), required_postures=(), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2325, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 390, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1462, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:19</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1453</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.splash_Sim_seated'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(), required_postures=(&lt;class 'sims4.tuning.instances.posture_Swim'&gt;,), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1453, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:19</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1462</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.Solo_Stargazing'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(&lt;class 'sims4.tuning.instances.posture_Swim'&gt;, &lt;class 'sims4.tuning.instances.posture_floating'&gt;, &lt;class 'sims4.tuning.instances.posture_IslandCanoe'&gt;, &lt;class 'sims4.tuning.instances.posture_floating'&gt;, &lt;class 'sims4.tuning.instances.posture_WaterScooter'&gt;, &lt;class 'sims4.tuning.instances.posture_IslandCanoe_Sit'&gt;, &lt;class 'sims4.tuning.instances.posture_IslandCanoe_Stand'&gt;), required_postures=(), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 721, in __new__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 390, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1462, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:19</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1453</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.pool_Splash_Social'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(), required_postures=(&lt;class 'sims4.tuning.instances.posture_Swim'&gt;,), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1453, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>5f5fab28d34a2bb25ea32ecd</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-24 22:05:19</createtime><buildsignature>Local.Unknown.Unknown.1.62.67.1020-1.200.000.442.Release</buildsignature><categoryid>test_variants.py:1453</categoryid><desyncid>5f5fab28d34a2bb25ea32ecd</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.pool_pee_in_pool'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 203, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 174, in wrapper&#13;&#10;KeyError: (PostureTest(container_supports=None, prohibited_postures=(), required_postures=(&lt;class 'sims4.tuning.instances.posture_Swim'&gt;,), subject=ParticipantTypeActorTargetSim.Actor, target=None, tooltip=None), frozenset({('actors', (&lt;sim '' 0xe150b1a07b3017f&gt;,))}))&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2315, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 567, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 176, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1453, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'&#13;&#10;rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
</root>